#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $SPAM_REPO == "Tianabot" ]]
    then
        echo "aHR0cHM6Ly9jb2RlbG9hZC5naXRodWIuY29tL2hhY2tlcndvcmxkeXQvVGlhbmFib3QvemlwL21haW4=" | base64 -d
    elif [[ $SPAM_REPO == "Tianabot" ]]
    then
        echo "aHR0cHM6Ly9jb2RlbG9hZC5naXRodWIuY29tL2hhY2tlcndvcmxkeXQvVGlhbmFib3QvemlwL21haW4=" | base64 -d
    elif [[ $SPAM_REPO =~ $regex ]]
    then
        if [[ $SPAM_REPO_BRANCH ]]
        then
            echo "${SPAM_REPO}/archive/${SPAM_REPO_BRANCH}.zip"
        else
            echo "${SPAM_REPO}/archive/main.zip"
        fi
    else
        echo "aHR0cHM6Ly9jb2RlbG9hZC5naXRodWIuY29tL2hhY2tlcndvcmxkeXQvVGlhbmFib3QvemlwL21haW4=" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="Tianabot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HELLPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $HELLPATH
    echo "  • Starting Hw Group Management •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m Tianabot
}

start_bot
